-- Insert default materials
INSERT INTO materials (name, unit, price, is_default) VALUES
('Baustelle einrichten', 'pauschal', 120.00, TRUE),
('Grundieren', 'm²', 3.00, TRUE),
('Abdichtung Dusch-/Wannenbereich', 'm²', 12.00, TRUE),
('Dichtbänder / -ecken / -manschetten', 'Stück', 9.50, TRUE),
('Fliesenverlegung (Wand/Boden)', 'm²', 60.00, TRUE),
('Sockelverlegung', 'lfm', 10.00, TRUE),
('Silikonfugen', 'lfm', 8.00, TRUE),
('Schienen setzen (Edelstahl/Alu)', 'lfm', 12.00, TRUE),
('Sanitär-/Elektroanschlüsse vorbereiten', 'Stück', 6.00, TRUE),
('Estrich ausgleichen / dünn spachteln', 'm²', 9.00, TRUE),
('Treppenstufen verlegen', 'Stück', 95.00, TRUE),
('Podest (z. B. Duschpodest)', 'Stück', 160.00, TRUE),
('Fensterbankmontage (nur Arbeit)', 'lfm', 35.00, TRUE),
('Verbrauchsmaterial pauschal', 'pauschal', 250.00, TRUE),
('CM-Messung', 'Stück', 70.00, TRUE),
('Stundenlohn Arbeiten', 'Stunde', 55.00, TRUE),
('Beratung / Planung', 'Stunde', 60.00, TRUE),
('Aufmaß', 'pauschal', 75.00, TRUE),
('Materialbeschaffung', 'pauschal', 30.00, TRUE),
('Baustellenkoordination', 'Stunde', 60.00, TRUE),
('Anfahrt', 'pauschal', 25.00, TRUE),
('Badewanne einmauern', 'Stück', 130.00, TRUE),
('Baraprofile setzen (inkl. Klebung)', 'lfm', 18.00, TRUE),
('Dicht-/Entkopplungsmatten verlegen', 'm²', 14.00, TRUE),
('Duschwannen einmauern', 'Stück', 135.00, TRUE),
('Fliesenverlegung 30x30', 'm²', 57.00, TRUE),
('Fliesenverlegung 30x60', 'm²', 60.00, TRUE),
('Fliesenverlegung 45x90', 'm²', 66.00, TRUE),
('Fliesenverlegung 60x60', 'm²', 68.00, TRUE),
('Fliesenverlegung 60x120', 'm²', 72.00, TRUE),
('Fliesenverlegung 75x75', 'm²', 75.00, TRUE),
('Fliesenverlegung 80x80', 'm²', 78.00, TRUE),
('Fliesenverlegung 90x90', 'm²', 80.00, TRUE),
('Gefälleestrich', 'm²', 26.00, TRUE),
('Mauerarbeiten', 'Stunde', 55.00, TRUE),
('Niesche herstellen (inkl. Abdichtung)', 'Stück', 95.00, TRUE),
('PVC-Schienen setzen', 'lfm', 8.50, TRUE),
('Randdämmstreifen einbauen', 'lfm', 4.00, TRUE),
('Rückbau Fliesen/Mörtelbett', 'pauschal', 150.00, TRUE),
('Verputzen (z. B. Bad mit Zementputz)', 'pauschal', 180.00, TRUE),
('Wände spachteln (inkl. Gewebeeinlage)', 'm²', 11.00, TRUE);
